block_id = "3"
direction_id = "0"
route_id = "V"
service_id = "3"
shape_id = "V_Limited_OB"
trip_headsign = "Outbound to West Village - No Service to 2080 Tilia (Limited)"
trip_id = "V_3_outbound_limited_0725"
