stop_code = "22606"
stop_desc = "Vet Med Parking Shuttle EB"
stop_id = "22606"
stop_lat = "38.532513"
stop_lon = "-121.760613"
stop_name = "Garrod Drive at Putah Creek Lodge Parking Lot"
zone_id = "0"
