feed_contact_email = "jjflynn@ucdavis.edu"
feed_contact_url = "http://unitrans.ucdavis.edu"
feed_end_date = "20230106"
feed_lang = "en"
feed_publisher_name = "Unitrans"
feed_publisher_url = "http://unitrans.ucdavis.edu"
feed_start_date = "20220711"
feed_version = "Sept2022-Fall2022_V1"
